// Generated by gencpp from file traj_utils/DataDisp.msg
// DO NOT EDIT!


#ifndef TRAJ_UTILS_MESSAGE_DATADISP_H
#define TRAJ_UTILS_MESSAGE_DATADISP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace traj_utils
{
template <class ContainerAllocator>
struct DataDisp_
{
  typedef DataDisp_<ContainerAllocator> Type;

  DataDisp_()
    : header()
    , a(0.0)
    , b(0.0)
    , c(0.0)
    , d(0.0)
    , e(0.0)  {
    }
  DataDisp_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , a(0.0)
    , b(0.0)
    , c(0.0)
    , d(0.0)
    , e(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _a_type;
  _a_type a;

   typedef double _b_type;
  _b_type b;

   typedef double _c_type;
  _c_type c;

   typedef double _d_type;
  _d_type d;

   typedef double _e_type;
  _e_type e;





  typedef boost::shared_ptr< ::traj_utils::DataDisp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traj_utils::DataDisp_<ContainerAllocator> const> ConstPtr;

}; // struct DataDisp_

typedef ::traj_utils::DataDisp_<std::allocator<void> > DataDisp;

typedef boost::shared_ptr< ::traj_utils::DataDisp > DataDispPtr;
typedef boost::shared_ptr< ::traj_utils::DataDisp const> DataDispConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traj_utils::DataDisp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traj_utils::DataDisp_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::traj_utils::DataDisp_<ContainerAllocator1> & lhs, const ::traj_utils::DataDisp_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.a == rhs.a &&
    lhs.b == rhs.b &&
    lhs.c == rhs.c &&
    lhs.d == rhs.d &&
    lhs.e == rhs.e;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::traj_utils::DataDisp_<ContainerAllocator1> & lhs, const ::traj_utils::DataDisp_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace traj_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::traj_utils::DataDisp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traj_utils::DataDisp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_utils::DataDisp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_utils::DataDisp_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_utils::DataDisp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_utils::DataDisp_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traj_utils::DataDisp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8cc3ee9eb5e91a9074c1e70ea8f247fa";
  }

  static const char* value(const ::traj_utils::DataDisp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8cc3ee9eb5e91a90ULL;
  static const uint64_t static_value2 = 0x74c1e70ea8f247faULL;
};

template<class ContainerAllocator>
struct DataType< ::traj_utils::DataDisp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traj_utils/DataDisp";
  }

  static const char* value(const ::traj_utils::DataDisp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traj_utils::DataDisp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64 a\n"
"float64 b\n"
"float64 c\n"
"float64 d\n"
"float64 e\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::traj_utils::DataDisp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traj_utils::DataDisp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
      stream.next(m.d);
      stream.next(m.e);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DataDisp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traj_utils::DataDisp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traj_utils::DataDisp_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<double>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<double>::stream(s, indent + "  ", v.c);
    s << indent << "d: ";
    Printer<double>::stream(s, indent + "  ", v.d);
    s << indent << "e: ";
    Printer<double>::stream(s, indent + "  ", v.e);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAJ_UTILS_MESSAGE_DATADISP_H
