(cl:in-package traj_utils-msg)
(cl:export '(DRONE_ID-VAL
          DRONE_ID
          TRAJ_ID-VAL
          TRAJ_ID
          START_TIME-VAL
          START_TIME
          ORDER-VAL
          ORDER
          START_P-VAL
          START_P
          START_V-VAL
          START_V
          START_A-VAL
          START_A
          END_P-VAL
          END_P
          END_V-VAL
          END_V
          END_A-VAL
          END_A
          INNER_X-VAL
          INNER_X
          INNER_Y-VAL
          INNER_Y
          INNER_Z-VAL
          INNER_Z
          DURATION-VAL
          DURATION
))