// Generated by gencpp from file quadrotor_msgs/GoalSet.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_GOALSET_H
#define QUADROTOR_MSGS_MESSAGE_GOALSET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct GoalSet_
{
  typedef GoalSet_<ContainerAllocator> Type;

  GoalSet_()
    : drone_id(0)
    , goal()  {
      goal.assign(0.0);
  }
  GoalSet_(const ContainerAllocator& _alloc)
    : drone_id(0)
    , goal()  {
  (void)_alloc;
      goal.assign(0.0);
  }



   typedef int16_t _drone_id_type;
  _drone_id_type drone_id;

   typedef boost::array<float, 3>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::quadrotor_msgs::GoalSet_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::GoalSet_<ContainerAllocator> const> ConstPtr;

}; // struct GoalSet_

typedef ::quadrotor_msgs::GoalSet_<std::allocator<void> > GoalSet;

typedef boost::shared_ptr< ::quadrotor_msgs::GoalSet > GoalSetPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::GoalSet const> GoalSetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::GoalSet_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::GoalSet_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::GoalSet_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::GoalSet_<ContainerAllocator2> & rhs)
{
  return lhs.drone_id == rhs.drone_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::GoalSet_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::GoalSet_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::GoalSet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::GoalSet_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::GoalSet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::GoalSet_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::GoalSet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::GoalSet_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::GoalSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "647346ea582a0f372d5aad4ae220f0b2";
  }

  static const char* value(const ::quadrotor_msgs::GoalSet_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x647346ea582a0f37ULL;
  static const uint64_t static_value2 = 0x2d5aad4ae220f0b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::GoalSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/GoalSet";
  }

  static const char* value(const ::quadrotor_msgs::GoalSet_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::GoalSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 drone_id\n"
"float32[3] goal\n"
;
  }

  static const char* value(const ::quadrotor_msgs::GoalSet_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::GoalSet_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.drone_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoalSet_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::GoalSet_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::GoalSet_<ContainerAllocator>& v)
  {
    s << indent << "drone_id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.drone_id);
    s << indent << "goal[]" << std::endl;
    for (size_t i = 0; i < v.goal.size(); ++i)
    {
      s << indent << "  goal[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.goal[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_GOALSET_H
